name: wasteagram
description: Personal exporation into the Flutter framework.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  app_settings: 4.0.2
  cloud_firestore: ^0.14.0
  #cloud_firestore: ^0.11.0+2
  cupertino_icons: ^0.1.3
  datetime_picker_formfield: ^1.0.0
  firebase_auth: ^0.18.0
  firebase_core: 0.5.0
  firebase_storage: ^4.0.0
  flutter:
    sdk: flutter
  google_sign_in: "^4.5.1"
  image_picker: ^0.6.7+4

  intl: ^0.16.1
  location: ^3.0.0
  shared_preferences: ^0.5.8
  rxdart: 0.20.0

dev_dependencies:
  #firestore_mock: ^0.0.6
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  path_provider: ^1.6.11
  test: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
  - assets/testing/test_image.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
